package cn.net.yzl.crm.customer.dao;

import cn.net.yzl.crm.customer.model.db.MemberProductEffect;
import org.springframework.stereotype.Repository;

@Repository
public interface MemberProductEffectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_product_effect
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_product_effect
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int insert(MemberProductEffect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_product_effect
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int insertSelective(MemberProductEffect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_product_effect
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    MemberProductEffect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_product_effect
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int updateByPrimaryKeySelective(MemberProductEffect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_product_effect
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int updateByPrimaryKey(MemberProductEffect record);
}