package cn.net.yzl.crm.customer.dao;

import cn.net.yzl.crm.customer.model.db.MemberDisease;
import org.springframework.stereotype.Repository;

@Repository
public interface MemberDiseaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int insert(MemberDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int insertSelective(MemberDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    MemberDisease selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int updateByPrimaryKeySelective(MemberDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int updateByPrimaryKey(MemberDisease record);
}