package cn.net.yzl.crm.customer.dao;

import cn.net.yzl.crm.customer.model.db.MemberDisease;
import cn.net.yzl.crm.customer.vo.MemberDiseaseIdUpdateVO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MemberDiseaseMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int insert(MemberDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int insertSelective(MemberDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    MemberDisease selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int updateByPrimaryKeySelective(MemberDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_disease
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int updateByPrimaryKey(MemberDisease record);
    /**
     * @Author: lichanghong
     * @Description:
     * @Date: 2021/1/25 9:11 下午
     * @param codes
     * @Return:
     */
    List<cn.net.yzl.crm.customer.model.mogo.MemberDisease> queryByMemberCodes(List<String> codes);

    /**
     * 替换顾客病症id
     * wangzhe
     * 2021-02-05
     * @param vo
     * @return
     */
    Integer updateMemberDiseaseByDiseaseId(MemberDiseaseIdUpdateVO vo);

}