package cn.net.yzl.crm.customer.dao;

import cn.net.yzl.crm.customer.model.db.ProductConsultation;
import org.springframework.stereotype.Repository;

@Repository
public interface ProductConsultationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_consultation
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_consultation
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int insert(ProductConsultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_consultation
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int insertSelective(ProductConsultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_consultation
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    ProductConsultation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_consultation
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int updateByPrimaryKeySelective(ProductConsultation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_consultation
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    int updateByPrimaryKey(ProductConsultation record);
}