package cn.net.yzl.crm.customer.dao;

import cn.net.yzl.crm.customer.dto.address.ReveiverAddressDto;
import cn.net.yzl.crm.customer.dto.member.MemberReveiverAddressSerchDTO;
import cn.net.yzl.crm.customer.model.db.ReveiverAddress;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ReveiverAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reveiver_address
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reveiver_address
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    int insert(ReveiverAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reveiver_address
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    int insertSelective(ReveiverAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reveiver_address
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    ReveiverAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reveiver_address
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    int updateByPrimaryKeySelective(ReveiverAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reveiver_address
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    int updateByPrimaryKey(ReveiverAddress record);


    List<ReveiverAddressDto> getReveiverAddressByMemberCard(@Param("memberCard") String memberCard);

    List<ReveiverAddressDto> getReveiverAddressByPage(MemberReveiverAddressSerchDTO serchDTO);

    int selectDefaultCountByMemberCard(@Param("memberCard") String memberCard);

}