package cn.net.yzl.crm.customer.model.db;

import java.util.Date;

public class MemberDisease {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_disease.id
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_disease.member_card
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    private String memberCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_disease.disease_id
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    private Integer diseaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_disease.disease_name
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    private String diseaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_disease.disease_descrip
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    private String diseaseDescrip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_disease.del_flag
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_disease.create_no
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    private String createNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_disease.create_time
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_disease.id
     *
     * @return the value of member_disease.id
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_disease.id
     *
     * @param id the value for member_disease.id
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_disease.member_card
     *
     * @return the value of member_disease.member_card
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public String getMemberCard() {
        return memberCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_disease.member_card
     *
     * @param memberCard the value for member_disease.member_card
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public void setMemberCard(String memberCard) {
        this.memberCard = memberCard == null ? null : memberCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_disease.disease_id
     *
     * @return the value of member_disease.disease_id
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public Integer getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_disease.disease_id
     *
     * @param diseaseId the value for member_disease.disease_id
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_disease.disease_name
     *
     * @return the value of member_disease.disease_name
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public String getDiseaseName() {
        return diseaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_disease.disease_name
     *
     * @param diseaseName the value for member_disease.disease_name
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName == null ? null : diseaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_disease.disease_descrip
     *
     * @return the value of member_disease.disease_descrip
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public String getDiseaseDescrip() {
        return diseaseDescrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_disease.disease_descrip
     *
     * @param diseaseDescrip the value for member_disease.disease_descrip
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public void setDiseaseDescrip(String diseaseDescrip) {
        this.diseaseDescrip = diseaseDescrip == null ? null : diseaseDescrip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_disease.del_flag
     *
     * @return the value of member_disease.del_flag
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_disease.del_flag
     *
     * @param delFlag the value for member_disease.del_flag
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_disease.create_no
     *
     * @return the value of member_disease.create_no
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public String getCreateNo() {
        return createNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_disease.create_no
     *
     * @param createNo the value for member_disease.create_no
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public void setCreateNo(String createNo) {
        this.createNo = createNo == null ? null : createNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_disease.create_time
     *
     * @return the value of member_disease.create_time
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_disease.create_time
     *
     * @param createTime the value for member_disease.create_time
     *
     * @mbggenerated Mon Jan 25 17:10:49 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}