package cn.net.yzl.crm.customer.model.db;

import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

public class ReveiverAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.id
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.reveiver_address_code
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private Integer reveiverAddressCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_card
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String memberCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_mobile
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String memberMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_province_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private Integer memberProvinceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_province_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String memberProvinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_city_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private Integer memberCityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_city_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String memberCityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_county_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private Integer memberCountyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_county_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String memberCountyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_street_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private Integer memberStreetNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_street_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String memberStreetName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.member_address
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String memberAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.status
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.create_time
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.create_code
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String createCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.update_time
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reveiver_address.update_code
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    private String updateCode;


    @ApiModelProperty(value = "是否是默认收货地址:0=不是,1=是",name = "defaultFlag",required = false)
    private Integer defaultFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.id
     *
     * @return the value of reveiver_address.id
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.id
     *
     * @param id the value for reveiver_address.id
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.reveiver_address_code
     *
     * @return the value of reveiver_address.reveiver_address_code
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public Integer getReveiverAddressCode() {
        return reveiverAddressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.reveiver_address_code
     *
     * @param reveiverAddressCode the value for reveiver_address.reveiver_address_code
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setReveiverAddressCode(Integer reveiverAddressCode) {
        this.reveiverAddressCode = reveiverAddressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_card
     *
     * @return the value of reveiver_address.member_card
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getMemberCard() {
        return memberCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_card
     *
     * @param memberCard the value for reveiver_address.member_card
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberCard(String memberCard) {
        this.memberCard = memberCard == null ? null : memberCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_name
     *
     * @return the value of reveiver_address.member_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_name
     *
     * @param memberName the value for reveiver_address.member_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_mobile
     *
     * @return the value of reveiver_address.member_mobile
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getMemberMobile() {
        return memberMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_mobile
     *
     * @param memberMobile the value for reveiver_address.member_mobile
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberMobile(String memberMobile) {
        this.memberMobile = memberMobile == null ? null : memberMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_province_no
     *
     * @return the value of reveiver_address.member_province_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public Integer getMemberProvinceNo() {
        return memberProvinceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_province_no
     *
     * @param memberProvinceNo the value for reveiver_address.member_province_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberProvinceNo(Integer memberProvinceNo) {
        this.memberProvinceNo = memberProvinceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_province_name
     *
     * @return the value of reveiver_address.member_province_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getMemberProvinceName() {
        return memberProvinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_province_name
     *
     * @param memberProvinceName the value for reveiver_address.member_province_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberProvinceName(String memberProvinceName) {
        this.memberProvinceName = memberProvinceName == null ? null : memberProvinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_city_no
     *
     * @return the value of reveiver_address.member_city_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public Integer getMemberCityNo() {
        return memberCityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_city_no
     *
     * @param memberCityNo the value for reveiver_address.member_city_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberCityNo(Integer memberCityNo) {
        this.memberCityNo = memberCityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_city_name
     *
     * @return the value of reveiver_address.member_city_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getMemberCityName() {
        return memberCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_city_name
     *
     * @param memberCityName the value for reveiver_address.member_city_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberCityName(String memberCityName) {
        this.memberCityName = memberCityName == null ? null : memberCityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_county_no
     *
     * @return the value of reveiver_address.member_county_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public Integer getMemberCountyNo() {
        return memberCountyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_county_no
     *
     * @param memberCountyNo the value for reveiver_address.member_county_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberCountyNo(Integer memberCountyNo) {
        this.memberCountyNo = memberCountyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_county_name
     *
     * @return the value of reveiver_address.member_county_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getMemberCountyName() {
        return memberCountyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_county_name
     *
     * @param memberCountyName the value for reveiver_address.member_county_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberCountyName(String memberCountyName) {
        this.memberCountyName = memberCountyName == null ? null : memberCountyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_street_no
     *
     * @return the value of reveiver_address.member_street_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public Integer getMemberStreetNo() {
        return memberStreetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_street_no
     *
     * @param memberStreetNo the value for reveiver_address.member_street_no
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberStreetNo(Integer memberStreetNo) {
        this.memberStreetNo = memberStreetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_street_name
     *
     * @return the value of reveiver_address.member_street_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getMemberStreetName() {
        return memberStreetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_street_name
     *
     * @param memberStreetName the value for reveiver_address.member_street_name
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberStreetName(String memberStreetName) {
        this.memberStreetName = memberStreetName == null ? null : memberStreetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.member_address
     *
     * @return the value of reveiver_address.member_address
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getMemberAddress() {
        return memberAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.member_address
     *
     * @param memberAddress the value for reveiver_address.member_address
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setMemberAddress(String memberAddress) {
        this.memberAddress = memberAddress == null ? null : memberAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.status
     *
     * @return the value of reveiver_address.status
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.status
     *
     * @param status the value for reveiver_address.status
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.create_time
     *
     * @return the value of reveiver_address.create_time
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.create_time
     *
     * @param createTime the value for reveiver_address.create_time
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.create_code
     *
     * @return the value of reveiver_address.create_code
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getCreateCode() {
        return createCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.create_code
     *
     * @param createCode the value for reveiver_address.create_code
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setCreateCode(String createCode) {
        this.createCode = createCode == null ? null : createCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.update_time
     *
     * @return the value of reveiver_address.update_time
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.update_time
     *
     * @param updateTime the value for reveiver_address.update_time
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reveiver_address.update_code
     *
     * @return the value of reveiver_address.update_code
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public String getUpdateCode() {
        return updateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reveiver_address.update_code
     *
     * @param updateCode the value for reveiver_address.update_code
     *
     * @mbggenerated Mon Jan 25 17:26:03 CST 2021
     */
    public void setUpdateCode(String updateCode) {
        this.updateCode = updateCode == null ? null : updateCode.trim();
    }

    public Integer getDefaultFlag() {
        return defaultFlag;
    }

    public void setDefaultFlag(Integer defaultFlag) {
        this.defaultFlag = defaultFlag;
    }
}